### ISSUE TITLE
Subject: Feature Request: Support for Loading Local .safetensors Files for SD1.5 and SDXL Models

### ISSUE THREAD

**Issue by katyukuki** [showlab/X-Adapter#13]
Dear [X-Adapter Development Team],

I hope this message finds you well. I am writing to express my appreciation for your work on the X-Adapter project, which I have found to be incredibly useful and well-crafted. Your efforts have undoubtedly contributed significantly to the community, and I am grateful for your dedication.

I am reaching out to kindly request a feature enhancement that I believe would add substantial value to X-Adapter. Specifically, I am interested in the ability to load .safetensors format files for both the SD1.5 and SDXL models from a local source. This feature would greatly benefit users like myself who work in environments where direct access to these models via the internet is restricted or prefer to use locally stored models for performance reasons.

The ability to specify local .safetensors files for model loading could enhance the flexibility and usability of X-Adapter, allowing for a wider range of applications and environments. I understand that implementing this feature may require significant effort and resources, but I believe it would be a valuable addition to the already impressive capabilities of X-Adapter.

I am more than willing to provide further details or clarification if needed. Additionally, I am open to contributing to this feature's development or testing, should you find it feasible to consider this request.

Thank you for considering my request, and once again, I would like to express my deepest appreciation for your work on the X-Adapter project. Your commitment to open-source development and the betterment of the community is truly inspiring.

Warm regards,

[katyukuki]

**Comment by Semolce9** [comment]
Thank you for your suggestion. You can specify `--sdxl_path`, `--path_vae_sdxl` and `--base_path` to the local stored folder while it's true that we do not support .safetensors file now. I will really appreciate it if you can contribute to this feature. I think we can add a `from_pretrained` function in pipeline like this:

`pipeline = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", use_safetensors=True)`

 Feel free to pull a request and I will merge it after testing.

**Comment by katyukuki** [comment]
Hi, thanks for the reply and advice.
I tried to use the function you advised last night in windows environment, but it didn't look at the local environment folder and gave me a code error.
I put it in offline mode and that didn't solve the problem, but I'll give it a few more tries.

**Comment by Semolce9** [comment]
Thank you for trying. I will get a look at it later today.

**Comment by katyukuki** [comment]
Hello,
I was wondering if you could help me with the last model loading.
In the meantime, both SD1.5 and sdxl succeeded in loading models.
But there was another problem that came up, and I couldn't figure out which place it was caused by.
The error code is
`Traceback (most recent call last):
  File "L:\X-Adapter\inference.py", line 124, in <module>
    run_inference(args)
  File "L:\X-Adapter\inference.py", line 117, in run_inference
    inference_lora(args)
  File "L:\X-Adapter\scripts\inference_lora.py", line 274, in inference_lora
    pipe(prompt=prompt, prompt_sd1_5=prompt_sd1_5, negative_prompt=negative_prompt, width=1024,
  File "L:\X-Adapter\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "L:\X-Adapter\pipeline\pipeline_sd_xl_adapter.py", line 888, in __call__
    unet_output = self.unet_sd1_5(
  File "L:\X-Adapter\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "L:\X-Adapter\venv\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
TypeError: UNet2DConditionModel.forward() got an unexpected keyword argument 'return_hidden_states'`

**Comment by katyukuki** [comment]
P.S. The successful way to load the model is
`# load SD1.5
    sdpipline = StableDiffusionPipeline.from_single_file(f"{path}")
    noise_scheduler_sd1_5 = sdpipline.scheduler
    tokenizer_sd1_5 = sdpipline.tokenizer
    text_encoder_sd1_5  = sdpipline.text_encoder
    vae_sd1_5 = sdpipline.vae
    unet_sd1_5 = sdpipline.unet`
`sdpipline2 = StableDiffusionXLPipeline.from_single_file(f"{path_sdxl}")
    tokenizer_one  = sdpipline2.tokenizer
    tokenizer_two  = sdpipline2.tokenizer_2
    text_encoder_cls_one =  sdpipline2.text_encoder
    text_encoder_cls_two =  sdpipline2.text_encoder_2
    noise_scheduler = sdpipline2.scheduler
    text_encoder_one =  sdpipline2.text_encoder
    text_encoder_two =  sdpipline2.text_encoder_2
    vae  = sdpipline2.vae
    unet = sdpipline2.unet`

**Comment by katyukuki** [comment]
Report.
In the meantime, I was able to change the program so that the local model can be processed by reading SD1.5 and sdXL.
I may be missing something, but I will close this page for now.
Thanks for all the advice.

**Comment by katyukuki** [comment]
Thanks

**Comment by Semolce9** [comment]
Hi. Sorry I'm very busy these days. May I know current progress?

**Comment by Semolce9** [comment]
I see. I think you can use this code in your own implementation if it works. I'll write a more readable code in this repo.

**Comment by katyukuki** [comment]
Thanks, looking forward to the implementation!
